# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from qcc.executor.v1 import executor_pb2 as qcc_dot_executor_dot_v1_dot_executor__pb2


class ExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunCircuit = channel.unary_unary(
                '/qcc.executor.v1.Executor/RunCircuit',
                request_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.RunCircuitRequest.SerializeToString,
                response_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.RunCircuitResponse.FromString,
                _registered_method=True)
        self.ConvertSource = channel.unary_unary(
                '/qcc.executor.v1.Executor/ConvertSource',
                request_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ConvertSourceRequest.SerializeToString,
                response_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ConvertSourceResponse.FromString,
                _registered_method=True)
        self.DrawCircuit = channel.unary_unary(
                '/qcc.executor.v1.Executor/DrawCircuit',
                request_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.DrawCircuitRequest.SerializeToString,
                response_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.DrawCircuitResponse.FromString,
                _registered_method=True)
        self.ScheduleCircuit = channel.unary_unary(
                '/qcc.executor.v1.Executor/ScheduleCircuit',
                request_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ScheduleCircuitRequest.SerializeToString,
                response_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ScheduleCircuitResponse.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/qcc.executor.v1.Executor/SubmitTask',
                request_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.WatchTask = channel.unary_stream(
                '/qcc.executor.v1.Executor/WatchTask',
                request_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.WatchTaskRequest.SerializeToString,
                response_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.WatchTaskResponse.FromString,
                _registered_method=True)
        self.FetchTaskResult = channel.unary_unary(
                '/qcc.executor.v1.Executor/FetchTaskResult',
                request_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.FetchTaskResultRequest.SerializeToString,
                response_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.FetchTaskResultResponse.FromString,
                _registered_method=True)
        self.ProbeBackend = channel.unary_unary(
                '/qcc.executor.v1.Executor/ProbeBackend',
                request_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ProbeBackendRequest.SerializeToString,
                response_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ProbeBackendResponse.FromString,
                _registered_method=True)


class ExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunCircuit(self, request, context):
        """RunCircuit transpiles, submits, and waits for results in a single RPC.
        Returns DONE on success or FAILED with a Circuit condition reason.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertSource(self, request, context):
        """ConvertSource translates a non-OpenQASM3 circuit source (e.g., a Qiskit
        Python module that exposes a top-level QuantumCircuit) into OpenQASM 3.
        Pure transform; no provider interaction.  Consumed by the controller
        before normal lifecycle when Circuit.spec.source.format != openqasm3.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrawCircuit(self, request, context):
        """DrawCircuit renders the circuit as ASCII (Qiskit's text drawer).  Pure
        transform; no provider interaction.  Consumed by the controller when
        Circuit.spec.mode == draw.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScheduleCircuit(self, request, context):
        """ScheduleCircuit transpiles the source against the given backend with
        scheduling_method='asap' and returns the resulting per-instruction
        timeline (start times in dt, durations, qubit indices).  Pure
        analysis — no shots consumed, no remote job created — but unlike
        DrawCircuit it does need a backend because scheduling is
        backend-specific (durations come from the backend's Target, and
        physical qubit assignment depends on layout/routing).  Consumed by
        the controller when Circuit.spec.mode == schedule.  Together with
        QPUStatus.dtSeconds the response gives readers the µs-scale
        envelope of a circuit (Ch1's "9466 dt ≈ 1.89 µs" anchor).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """SubmitTask submits a circuit asynchronously and returns the task_id
        assigned by the adapter (typically the provider's job ID).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchTask(self, request, context):
        """WatchTask streams TaskStatus updates until terminal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchTaskResult(self, request, context):
        """FetchTaskResult retrieves results for a terminal task.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProbeBackend(self, request, context):
        """ProbeBackend asks the executor to introspect a registered backend
        (local fake_* simulators and real IBM hardware today) and return
        its calibration-relevant metadata: qubit count, native gate
        set, coupling-map size, calibration timestamp, and gate/readout
        error medians.  The QPUReconciler calls this when a QPU registers
        and (in M2) on a TTL-driven refresh; the response populates
        QPU.status.{qubits,basisGates,couplingEdges,errorMedians,lastCalibrationTime}.

        Pure introspection — no job submission, no shots consumed.  See
        QCC-API.md §4.5 for the field-by-field mapping.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCircuit,
                    request_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.RunCircuitRequest.FromString,
                    response_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.RunCircuitResponse.SerializeToString,
            ),
            'ConvertSource': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertSource,
                    request_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ConvertSourceRequest.FromString,
                    response_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ConvertSourceResponse.SerializeToString,
            ),
            'DrawCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.DrawCircuit,
                    request_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.DrawCircuitRequest.FromString,
                    response_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.DrawCircuitResponse.SerializeToString,
            ),
            'ScheduleCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleCircuit,
                    request_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ScheduleCircuitRequest.FromString,
                    response_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ScheduleCircuitResponse.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.SubmitTaskRequest.FromString,
                    response_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'WatchTask': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchTask,
                    request_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.WatchTaskRequest.FromString,
                    response_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.WatchTaskResponse.SerializeToString,
            ),
            'FetchTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchTaskResult,
                    request_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.FetchTaskResultRequest.FromString,
                    response_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.FetchTaskResultResponse.SerializeToString,
            ),
            'ProbeBackend': grpc.unary_unary_rpc_method_handler(
                    servicer.ProbeBackend,
                    request_deserializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ProbeBackendRequest.FromString,
                    response_serializer=qcc_dot_executor_dot_v1_dot_executor__pb2.ProbeBackendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qcc.executor.v1.Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qcc.executor.v1.Executor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Executor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qcc.executor.v1.Executor/RunCircuit',
            qcc_dot_executor_dot_v1_dot_executor__pb2.RunCircuitRequest.SerializeToString,
            qcc_dot_executor_dot_v1_dot_executor__pb2.RunCircuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qcc.executor.v1.Executor/ConvertSource',
            qcc_dot_executor_dot_v1_dot_executor__pb2.ConvertSourceRequest.SerializeToString,
            qcc_dot_executor_dot_v1_dot_executor__pb2.ConvertSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrawCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qcc.executor.v1.Executor/DrawCircuit',
            qcc_dot_executor_dot_v1_dot_executor__pb2.DrawCircuitRequest.SerializeToString,
            qcc_dot_executor_dot_v1_dot_executor__pb2.DrawCircuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScheduleCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qcc.executor.v1.Executor/ScheduleCircuit',
            qcc_dot_executor_dot_v1_dot_executor__pb2.ScheduleCircuitRequest.SerializeToString,
            qcc_dot_executor_dot_v1_dot_executor__pb2.ScheduleCircuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qcc.executor.v1.Executor/SubmitTask',
            qcc_dot_executor_dot_v1_dot_executor__pb2.SubmitTaskRequest.SerializeToString,
            qcc_dot_executor_dot_v1_dot_executor__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/qcc.executor.v1.Executor/WatchTask',
            qcc_dot_executor_dot_v1_dot_executor__pb2.WatchTaskRequest.SerializeToString,
            qcc_dot_executor_dot_v1_dot_executor__pb2.WatchTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qcc.executor.v1.Executor/FetchTaskResult',
            qcc_dot_executor_dot_v1_dot_executor__pb2.FetchTaskResultRequest.SerializeToString,
            qcc_dot_executor_dot_v1_dot_executor__pb2.FetchTaskResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProbeBackend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qcc.executor.v1.Executor/ProbeBackend',
            qcc_dot_executor_dot_v1_dot_executor__pb2.ProbeBackendRequest.SerializeToString,
            qcc_dot_executor_dot_v1_dot_executor__pb2.ProbeBackendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
