# This rule is not used by the project quantum-circuit-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to qcc.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: quantum-circuit-controller
    app.kubernetes.io/managed-by: kustomize
  name: qpu-viewer-role
rules:
- apiGroups:
  - qcc.io
  resources:
  - qpus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qcc.io
  resources:
  - qpus/status
  verbs:
  - get
