//go:build !ignore_autogenerated

/*
Copyright 2026 ioaiaaii.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactRef) DeepCopyInto(out *ArtifactRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactRef.
func (in *ArtifactRef) DeepCopy() *ArtifactRef {
	if in == nil {
		return nil
	}
	out := new(ArtifactRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendSelector) DeepCopyInto(out *BackendSelector) {
	*out = *in
	if in.AllowedQPURefs != nil {
		in, out := &in.AllowedQPURefs, &out.AllowedQPURefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendSelector.
func (in *BackendSelector) DeepCopy() *BackendSelector {
	if in == nil {
		return nil
	}
	out := new(BackendSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Circuit) DeepCopyInto(out *Circuit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Circuit.
func (in *Circuit) DeepCopy() *Circuit {
	if in == nil {
		return nil
	}
	out := new(Circuit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Circuit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitList) DeepCopyInto(out *CircuitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Circuit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitList.
func (in *CircuitList) DeepCopy() *CircuitList {
	if in == nil {
		return nil
	}
	out := new(CircuitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CircuitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitSource) DeepCopyInto(out *CircuitSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitSource.
func (in *CircuitSource) DeepCopy() *CircuitSource {
	if in == nil {
		return nil
	}
	out := new(CircuitSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitSpec) DeepCopyInto(out *CircuitSpec) {
	*out = *in
	out.Source = in.Source
	if in.BackendSelector != nil {
		in, out := &in.BackendSelector, &out.BackendSelector
		*out = new(BackendSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.OptimizationLevel != nil {
		in, out := &in.OptimizationLevel, &out.OptimizationLevel
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.Transpile != nil {
		in, out := &in.Transpile, &out.Transpile
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Execute != nil {
		in, out := &in.Execute, &out.Execute
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitSpec.
func (in *CircuitSpec) DeepCopy() *CircuitSpec {
	if in == nil {
		return nil
	}
	out := new(CircuitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitStatus) DeepCopyInto(out *CircuitStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SelectionSummary != nil {
		in, out := &in.SelectionSummary, &out.SelectionSummary
		*out = new(SelectionSummary)
		**out = **in
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Transpile != nil {
		in, out := &in.Transpile, &out.Transpile
		*out = new(CircuitTranspileMetrics)
		**out = **in
	}
	if in.DrawingRef != nil {
		in, out := &in.DrawingRef, &out.DrawingRef
		*out = new(ArtifactRef)
		**out = **in
	}
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(ArtifactRef)
		**out = **in
	}
	if in.ConvertedRef != nil {
		in, out := &in.ConvertedRef, &out.ConvertedRef
		*out = new(ArtifactRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitStatus.
func (in *CircuitStatus) DeepCopy() *CircuitStatus {
	if in == nil {
		return nil
	}
	out := new(CircuitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitTranspileMetrics) DeepCopyInto(out *CircuitTranspileMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitTranspileMetrics.
func (in *CircuitTranspileMetrics) DeepCopy() *CircuitTranspileMetrics {
	if in == nil {
		return nil
	}
	out := new(CircuitTranspileMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPU) DeepCopyInto(out *QPU) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPU.
func (in *QPU) DeepCopy() *QPU {
	if in == nil {
		return nil
	}
	out := new(QPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QPU) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPUAccess) DeepCopyInto(out *QPUAccess) {
	*out = *in
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPUAccess.
func (in *QPUAccess) DeepCopy() *QPUAccess {
	if in == nil {
		return nil
	}
	out := new(QPUAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPUCapabilities) DeepCopyInto(out *QPUCapabilities) {
	*out = *in
	if in.MaxShots != nil {
		in, out := &in.MaxShots, &out.MaxShots
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPUCapabilities.
func (in *QPUCapabilities) DeepCopy() *QPUCapabilities {
	if in == nil {
		return nil
	}
	out := new(QPUCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPUCoherenceMedians) DeepCopyInto(out *QPUCoherenceMedians) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPUCoherenceMedians.
func (in *QPUCoherenceMedians) DeepCopy() *QPUCoherenceMedians {
	if in == nil {
		return nil
	}
	out := new(QPUCoherenceMedians)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPUErrorMedians) DeepCopyInto(out *QPUErrorMedians) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPUErrorMedians.
func (in *QPUErrorMedians) DeepCopy() *QPUErrorMedians {
	if in == nil {
		return nil
	}
	out := new(QPUErrorMedians)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPUInstructionDurationMedians) DeepCopyInto(out *QPUInstructionDurationMedians) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPUInstructionDurationMedians.
func (in *QPUInstructionDurationMedians) DeepCopy() *QPUInstructionDurationMedians {
	if in == nil {
		return nil
	}
	out := new(QPUInstructionDurationMedians)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPULastError) DeepCopyInto(out *QPULastError) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPULastError.
func (in *QPULastError) DeepCopy() *QPULastError {
	if in == nil {
		return nil
	}
	out := new(QPULastError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPUList) DeepCopyInto(out *QPUList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QPU, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPUList.
func (in *QPUList) DeepCopy() *QPUList {
	if in == nil {
		return nil
	}
	out := new(QPUList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QPUList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPUProcessor) DeepCopyInto(out *QPUProcessor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPUProcessor.
func (in *QPUProcessor) DeepCopy() *QPUProcessor {
	if in == nil {
		return nil
	}
	out := new(QPUProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPUSpec) DeepCopyInto(out *QPUSpec) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = new(QPUAccess)
		(*in).DeepCopyInto(*out)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(QPUCapabilities)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPUSpec.
func (in *QPUSpec) DeepCopy() *QPUSpec {
	if in == nil {
		return nil
	}
	out := new(QPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QPUStatus) DeepCopyInto(out *QPUStatus) {
	*out = *in
	if in.BasisGates != nil {
		in, out := &in.BasisGates, &out.BasisGates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastCalibrationTime != nil {
		in, out := &in.LastCalibrationTime, &out.LastCalibrationTime
		*out = (*in).DeepCopy()
	}
	if in.ErrorMedians != nil {
		in, out := &in.ErrorMedians, &out.ErrorMedians
		*out = new(QPUErrorMedians)
		**out = **in
	}
	if in.CoherenceMedians != nil {
		in, out := &in.CoherenceMedians, &out.CoherenceMedians
		*out = new(QPUCoherenceMedians)
		**out = **in
	}
	if in.InstructionDurationMedians != nil {
		in, out := &in.InstructionDurationMedians, &out.InstructionDurationMedians
		*out = new(QPUInstructionDurationMedians)
		**out = **in
	}
	if in.Processor != nil {
		in, out := &in.Processor, &out.Processor
		*out = new(QPUProcessor)
		**out = **in
	}
	if in.QueueDepth != nil {
		in, out := &in.QueueDepth, &out.QueueDepth
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(QPULastError)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QPUStatus.
func (in *QPUStatus) DeepCopy() *QPUStatus {
	if in == nil {
		return nil
	}
	out := new(QPUStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectionSummary) DeepCopyInto(out *SelectionSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectionSummary.
func (in *SelectionSummary) DeepCopy() *SelectionSummary {
	if in == nil {
		return nil
	}
	out := new(SelectionSummary)
	in.DeepCopyInto(out)
	return out
}
