apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: executor
    app.kubernetes.io/name: {{ include "quantum-circuit-controller.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "quantum-circuit-controller.resourceName" (dict "suffix" "executor" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc
    port: 9000
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/component: executor
    app.kubernetes.io/name: {{ include "quantum-circuit-controller.name" . }}
  type: ClusterIP
