name: E2E Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - CITATION.cff
      - .zenodo.json
      - "LICENSE"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - ".github/workflows/ci.yml"
      - ".github/workflows/proto.yml"
      - ".github/workflows/docs.yml"
      - ".github/workflows/analysis.yml"
      - ".github/workflows/cache.yml"
      - ".github/workflows/cd.yml"
      - ".github/workflows/release.yml"
      - "deploy/**"
      - "examples/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - CITATION.cff
      - "LICENSE"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - ".github/workflows/ci.yml"
      - ".github/workflows/proto.yml"
      - ".github/workflows/docs.yml"
      - ".github/workflows/analysis.yml"
      - ".github/workflows/cache.yml"
      - ".github/workflows/cd.yml"
      - ".github/workflows/release.yml"
      - "deploy/**"
      - "examples/**"      

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-e2e:
    permissions:
      contents: read
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: true

      - name: Set up the toolchain
        uses: ./.github/actions/setup

      - name: Run e2e tests
        run: make test-e2e
